# Generated by Django 2.1.1 on 2018-12-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniurl',
            options={'ordering': ['date'], 'verbose_name': 'Mini URL', 'verbose_name_plural': 'Minis URL'},
        ),
    ]
