# Generated by Django 2.0.6 on 2018-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180607_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
