# Generated by Django 2.0.6 on 2018-06-12 07:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180611_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to=blog.models.Document.renommage, verbose_name='Document')),
            ],
        ),
    ]
